# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'study app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for study app
pod "Alamofire"

  target 'study appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'study appUITests' do
    # Pods for testing
  end

end
